name: On Pull Request

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  build:
    name: Build
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-build.yml@v1.8.0
    with:
      node_version: "22"
      release_mode: "no"
    secrets: inherit