name: On Pull Request To Main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  check-source-branch:
    name: Check Source Branch
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: ${{ github.head_ref }}
    steps:
      - name: Check source branch is either 'dev' or 'hotfix*'
        run: |
          echo "Source branch: ${SOURCE_BRANCH}"
          BRANCH="${SOURCE_BRANCH}"
          if [[ "$BRANCH" == "dev" || "$BRANCH" == hotfix* ]]; then
            echo "✅ Branch is allowed to target main."
          else
            echo "❌ Only branches named 'dev' or starting with 'hotfix' can target main."
            exit 1
          fi
  build:
    name: Build
    needs: check-source-branch
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-build.yml@v1.8.2
    with:
      node_version: "22"
      release_mode: "no"
    secrets: inherit