name: On push to dev

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: Build
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-build.yml@v1.8.2
    secrets: inherit

  dockerize:
    needs: build
    name: Dockerize
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-dockerize.yml@v1.8.2

  deploy-to-staging:
    needs: dockerize
    name: Deploy to Staging
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-deploy.yml@v1.8.2
    secrets: inherit