name: On push to dev

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: write

jobs:
  build-onboarding-api:
    name: Build Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-build.yml@feat-refactor
    secrets: inherit

  dockerize-onboarding-api:
    needs: build-onboarding-api
    name: Dockerize Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-dockerize.yml@feat-refactor

  deploy-onboarding-api:
    needs: dockerize-onboarding-api
    name: Deploy Onboarding API to STG
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-deploy.yml@feat-refactor
    with:
      gh_project_key: "std"
      gh_app_name: "onboarding-api"
    secrets: inherit