name: On push to dev

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: write

jobs:
  build-onboarding-api:
    name: Build Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-build.yml@v1.8.0
    secrets: inherit

  dockerize-onboarding-api:
    needs: build-onboarding-api
    name: Dockerize Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-dockerize.yml@v1.8.0

  deploy-onboarding-api:
    needs: dockerize-onboarding-api
    name: Deploy Onboarding API to STG
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-deploy.yml@v1.8.0
    secrets: inherit